spring.datasource.url=jdbc:mysql://localhost:3306/devvault
spring.datasource.username=root
spring.datasource.password=RAMShars@23

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080